# Generated by Django 3.2.7 on 2021-10-20 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
